// Auto-generated by generate-embedded.ts - DO NOT EDIT
// Contains source code as strings for binary mode compilation

export const embeddedSources: Record<string, string> = {
  'analyze.ts': `// AST analyzer - walks AST to collect definitions, references, diagnostics
// Used by $analyze phase as an alternative "compiler" that produces AnalysisResult

import type { Expr, Span } from './ast.ts';
export interface Definition {
  name: string;
  kind: 'let' | 'param' | 'const';
  loc?: Span;
}

export interface Reference {
  name: string;
  loc?: Span;
  definition?: Definition;  // Resolved reference, if found
}

export interface Diagnostic {
  message: string;
  severity: 'error' | 'warning' | 'info';
  loc?: Span;
}

export interface AnalysisResult {
  definitions: Definition[];
  references: Reference[];
  diagnostics: Diagnostic[];
}

// Scope for tracking definitions
type Scope = Map<string, Definition>;

// Analyze operations - what $ provides for analysis
export interface AnalyzeOps {
  // Main entry point - like compileProgram but produces AnalysisResult
  analyzeProgram: (expr: Expr) => AnalysisResult;

  // Walk an expression (extensions override to handle new node types)
  analyzeExpr: (expr: Expr) => void;

  // Scope management
  pushScope: () => void;
  popScope: () => void;

  // Recording
  define: (name: string, kind: Definition['kind'], loc?: Span) => Definition;
  reference: (name: string, loc?: Span) => void;
  diagnostic: (message: string, severity: Diagnostic['severity'], loc?: Span) => void;

  // State (accessible for inspection)
  definitions: Definition[];
  references: Reference[];
  diagnostics: Diagnostic[];

  // Builtins that shouldn't trigger "undefined" warnings
  builtins: Set<string>;
}

// Build analyzer ops - mutation style like other phases
export function build$analyze($: AnalyzeOps): void {
  // State
  $.definitions = [];
  $.references = [];
  $.diagnostics = [];
  $.builtins = new Set(['$operators']);

  // Scope stack
  const scopes: Scope[] = [new Map()];

  $.pushScope = () => {
    scopes.push(new Map());
  };

  $.popScope = () => {
    scopes.pop();
  };

  $.define = (name, kind, loc) => {
    const def: Definition = { name, kind, loc };
    $.definitions.push(def);
    // Add to current scope
    scopes[scopes.length - 1].set(name, def);
    return def;
  };

  // Resolve a name through scope chain
  const resolve = (name: string): Definition | undefined => {
    for (let i = scopes.length - 1; i >= 0; i--) {
      const def = scopes[i].get(name);
      if (def) return def;
    }
    return undefined;
  };

  $.reference = (name, loc) => {
    const definition = resolve(name);
    $.references.push({ name, loc, definition });

    // Warn about undefined references (unless builtin)
    if (!definition && !$.builtins.has(name)) {
      $.diagnostic(\`Cannot find name '\${name}'\`, 'error', loc);
    }
  };

  $.diagnostic = (message, severity, loc) => {
    $.diagnostics.push({ message, severity, loc });
  };

  // Main entry point
  $.analyzeProgram = (expr) => {
    // Reset state
    $.definitions = [];
    $.references = [];
    $.diagnostics = [];
    scopes.length = 1;
    scopes[0].clear();

    // Walk the AST
    $.analyzeExpr(expr);

    return {
      definitions: $.definitions,
      references: $.references,
      diagnostics: $.diagnostics,
    };
  };

  // Walk expressions - extensions can override for new node types
  $.analyzeExpr = (expr) => {
    switch (expr.type) {
      case 'Literal':
        // Nothing to analyze
        break;

      case 'Ident':
        $.reference(expr.name, expr.loc);
        break;

      case 'LetExpr':
        // Analyze value first (before name is in scope for non-recursive)
        // Actually, for letrec semantics, define first
        const def = $.define(expr.name, 'let', expr.nameLoc ?? expr.loc);
        $.analyzeExpr(expr.value);
        $.analyzeExpr(expr.body);
        break;

      case 'Lambda':
        $.pushScope();
        // Define parameters
        for (let i = 0; i < expr.params.length; i++) {
          const paramLoc = expr.paramsLoc?.[i];
          $.define(expr.params[i], 'param', paramLoc);
        }
        $.analyzeExpr(expr.body);
        $.popScope();
        break;

      case 'App':
        $.analyzeExpr(expr.fn);
        for (const arg of expr.args) {
          $.analyzeExpr(arg);
        }
        break;

      case 'IfExpr':
        $.analyzeExpr(expr.cond);
        $.analyzeExpr(expr.then);
        $.analyzeExpr(expr.else);
        break;

      case 'ObjectExpr':
        for (const prop of expr.properties) {
          $.analyzeExpr(prop.value);
        }
        break;

      case 'Index':
        $.analyzeExpr(expr.object);
        $.analyzeExpr(expr.key);
        break;

      case 'SetIndex':
        $.analyzeExpr(expr.object);
        $.analyzeExpr(expr.key);
        $.analyzeExpr(expr.value);
        break;

      default:
        // Unknown node type - extensions may have added it
        // They should override analyzeExpr to handle it
        break;
    }
  };
}

// Convenience: create analyzer
export function createAnalyzer(): AnalyzeOps {
  const $ = {} as AnalyzeOps;
  build$analyze($);
  return $;
}
`,
  'ast.ts': `/**
 * AST
 *
 * Represents the core format for communication between the parser and compiler.
 */

/**
 * Start and end offsets in the source text.
 */
export interface Span {
  start: number;  // byte offset of first character
  end: number;    // byte offset after last character
}

// Convert byte offset to line/column (1-indexed, for display)
export function posToLineCol(source: string, pos: number): { line: number; col: number } {
  let line = 1;
  let col = 1;
  for (let i = 0; i < pos && i < source.length; i++) {
    if (source[i] === '\\n') {
      line++;
      col = 1;
    } else {
      col++;
    }
  }
  return { line, col };
}

/**
 * All nodes have an optional source location (Span).
 */
export interface SpanExpr {
  loc?: Span;  // Source location (optional for backwards compat)
}

/**
 * All expression types.
 */
export type Expr =
  | LetExpr
  | LambdaExpr
  | AppExpr
  | IfExpr
  | ObjectExpr
  | ArrayExpr
  | IndexExpr
  | AssignIndex
  | LiteralExpr
  | IdentExpr;

/**
 * Represents \`let name = value in body\`.
 */
export interface LetExpr extends SpanExpr {
  type: 'LetExpr';
  name: string;
  nameLoc?: Span;  // Location of the binding name
  value: Expr;
  body: Expr;
}

/**
 * Represents \`(param, ...) => body\`.
 */
export interface LambdaExpr extends SpanExpr {
  type: 'Lambda';
  params: string[];
  paramsLoc?: Span[];  // Location of each parameter
  body: Expr;
}

/**
 * Represents \`fn(arg, ...)\`.
 */
export interface AppExpr extends SpanExpr {
  type: 'App';
  fn: Expr;
  args: Expr[];
}

/**
 * Represents \`if cond then then else else\`.
 */
export interface IfExpr extends SpanExpr {
  type: 'IfExpr';
  cond: Expr;
  then: Expr;
  else: Expr;
}

/**
 * Represents \`{ key: value, ... }\`.
 */
export interface ObjectExpr extends SpanExpr {
  type: 'ObjectExpr';
  properties: { key: string; keyLoc?: Span; value: Expr }[];
}

/**
 * Represents \`[elem, ...]\`.
 */
export interface ArrayExpr extends SpanExpr {
  type: 'ArrayExpr';
  elements: Expr[];
}

/**
 * Represents \`object[key]\`.
 */
export interface IndexExpr extends SpanExpr {
  type: 'Index';
  object: Expr;
  key: Expr;
}

/**
 * Represents \`object[key] = value\`.
 */
export interface AssignIndex extends SpanExpr {
  type: 'SetIndex';
  object: Expr;
  key: Expr;
  value: Expr;
}

/**
 * Represents e.g. \`42\`, \`"hello"\`, \`true\`, \`null\`.
 */
export interface LiteralExpr extends SpanExpr {
  type: 'Literal';
  value: number | string | boolean | null;
}

/**
 * Represents an identifier, e.g. \`foo\`.
 */
export interface IdentExpr extends SpanExpr {
  type: 'Ident';
  name: string;
}
`,
  'compile-helpers.ts': `import { Expr } from "./ast";
import { $compile } from "./compile";
import { build$emit, EmitOps, Env } from "./emit";
import { IR } from "./ir";
import { fix } from "./util";

const $emit: EmitOps = fix(build$emit);

// Convenience functions
export function compile(expr: Expr): IR {
  return $compile.compileProgram(expr);
}

export function compileToString(expr: Expr): string {
  return $emit.string(compile(expr));
}


export function compileToClosure(expr: Expr): ($: unknown) => Promise<unknown> {
  return $emit.programClosure(compile(expr))({}) as ($: unknown) => Promise<unknown>;
}
`,
  'compile.ts': `/**
 * Core compiler.
 */
import type { Expr, LetExpr, LambdaExpr, AppExpr, IfExpr, ObjectExpr, ArrayExpr, IndexExpr, AssignIndex, LiteralExpr, IdentExpr } from './ast.ts';
import { ir, type IR } from './ir.ts';
import { fix } from './util.ts';

// Compiler operations interface - all methods can be overridden by extensions
export interface CompilerOps {
  // Main entry point
  compileProgram: (expr: Expr) => IR;

  // Expression compilation (the extensible part)
  compileExpr: (expr: Expr) => IR;
  compileLet: (expr: LetExpr) => IR;
  compileLambda: (expr: LambdaExpr) => IR;
  compileApp: (expr: AppExpr) => IR;
  compileIf: (expr: IfExpr) => IR;
  compileObject: (expr: ObjectExpr) => IR;
  compileArray: (expr: ArrayExpr) => IR;
  compileIndex: (expr: IndexExpr) => IR;
  compileSetIndex: (expr: AssignIndex) => IR;
  compileLiteral: (expr: LiteralExpr) => IR;
  compileIdent: (expr: IdentExpr) => IR;

  // IR constructors (for extensions)
  ir: typeof ir;

  // Error reporting (throws CompileError)
  error: (message: string) => never;

  // Helpers
  escapeIdent: (s: string) => string;
}

// Compile-time error
export class CompileError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CompileError';
  }
}

// JS reserved words that need escaping
const JS_RESERVED = new Set([
  'break', 'case', 'catch', 'continue', 'debugger', 'default', 'delete',
  'do', 'else', 'finally', 'for', 'function', 'if', 'in', 'instanceof',
  'new', 'return', 'switch', 'this', 'throw', 'try', 'typeof', 'var',
  'void', 'while', 'with', 'class', 'const', 'enum', 'export', 'extends',
  'import', 'super', 'implements', 'interface', 'let', 'package', 'private',
  'protected', 'public', 'static', 'yield', 'await', 'async'
]);

// Base compiler builder - mutates $ to add all compiler operations
export function build$compile($: CompilerOps): void {
  // Expose IR constructors for extensions
  $.ir = ir;

  // Main entry point: just compile the expression
  // The program wrapper is handled by emit functions
  $.compileProgram = (expr) => $.compileExpr(expr);

  // Dispatch to specific compilers based on type
  $.compileExpr = (expr) => {
    switch (expr.type) {
      case 'LetExpr': return $.compileLet(expr);
      case 'Lambda': return $.compileLambda(expr);
      case 'App': return $.compileApp(expr);
      case 'IfExpr': return $.compileIf(expr);
      case 'ObjectExpr': return $.compileObject(expr);
      case 'ArrayExpr': return $.compileArray(expr);
      case 'Index': return $.compileIndex(expr);
      case 'SetIndex': return $.compileSetIndex(expr);
      case 'Literal': return $.compileLiteral(expr);
      case 'Ident': return $.compileIdent(expr);
      default:
        // For extensions that add new node types
        return ir.lit(\`/* unknown: \${(expr as any).type} */\`);
    }
  };

  // let x = v in body
  // Compiles to: $.let($env, "x", ($env) => <v>, ($env) => <body>)
  // Both thunks receive $env - the child environment with the binding
  $.compileLet = (expr) => {
    return ir.$('let',
      ir.var('$env'),
      ir.lit(expr.name),
      ir.arrow(['$env'], $.compileExpr(expr.value)),
      ir.arrow(['$env'], $.compileExpr(expr.body))
    );
  };

  // (x, y) => body
  // Compiles to: $.lambda($env, ["x", "y"], ($env) => <body>)
  // Captures $env for lexical scoping; body gets child $env with params bound
  $.compileLambda = (expr) => {
    return ir.$('lambda',
      ir.var('$env'),
      ir.array(...expr.params.map(p => ir.lit(p))),
      ir.arrow(['$env'], $.compileExpr(expr.body))
    );
  };

  // f(a, b)
  // Compiles to: $.call(<f>, [<a>, <b>])
  $.compileApp = (expr) => {
    return ir.$('call',
      $.compileExpr(expr.fn),
      ir.array(...expr.args.map(a => $.compileExpr(a)))
    );
  };

  // if c then a else b
  // Compiles to: $.if(<c>, ($env) => <a>, ($env) => <b>, $env)
  // Both branches receive current $env for any lookups inside
  $.compileIf = (expr) => {
    return ir.$('if',
      $.compileExpr(expr.cond),
      ir.arrow(['$env'], $.compileExpr(expr.then)),
      ir.arrow(['$env'], $.compileExpr(expr.else)),
      ir.var('$env')
    );
  };

  // { a: 1, b: 2 }
  // Compiles to: $.object({ a: <1>, b: <2> })
  $.compileObject = (expr) => {
    return ir.$('object',
      ir.object(expr.properties.map(p => ir.prop(p.key, $.compileExpr(p.value))))
    );
  };

  // [1, 2, 3]
  // Compiles to: $.array([<1>, <2>, <3>])
  $.compileArray = (expr) => {
    return ir.$('array',
      ir.array(...expr.elements.map(e => $.compileExpr(e)))
    );
  };

  // obj[key] (also handles obj.field which parses as Index with string literal key)
  // Compiles to: $.index(<obj>, <key>)
  $.compileIndex = (expr) => {
    return ir.$('index',
      $.compileExpr(expr.object),
      $.compileExpr(expr.key)
    );
  };

  // obj[key] = value
  // Compiles to: $.setIndex(<obj>, <key>, <value>)
  $.compileSetIndex = (expr) => {
    return ir.$('setIndex',
      $.compileExpr(expr.object),
      $.compileExpr(expr.key),
      $.compileExpr(expr.value)
    );
  };

  // 42, "hello", true, false
  // Compiles to: $.number(42), $.string("hello"), $.boolean(true/false)
  $.compileLiteral = (expr) => {
    if (typeof expr.value === 'number') {
      return ir.$('number', ir.lit(expr.value));
    }
    if (typeof expr.value === 'string') {
      return ir.$('string', ir.lit(expr.value));
    }
    if (typeof expr.value === 'boolean') {
      return ir.$('boolean', ir.lit(expr.value));
    }
    if (expr.value === null) {
      return ir.$('null');
    }
    return ir.lit(null);
  };

  // x
  // Compiles to: $.lookup($env, "x")
  // Looks up name in current $env
  $.compileIdent = (expr) => {
    return ir.$('lookup', ir.var('$env'), ir.lit(expr.name));
  };

  // Escape an identifier for use as a JS variable name
  $.escapeIdent = (s) => {
    if (JS_RESERVED.has(s)) {
      return \`_\${s}\`;
    }
    return s.replace(/[^a-zA-Z0-9_$]/g, '_');
  };

  // Error reporting - throws CompileError
  $.error = (message: string): never => {
    throw new CompileError(message);
  };
}

// Create the base compiler
export const $compile: CompilerOps = fix(build$compile);`,
  'emit.ts': `/**
 * Core emitter.
 */
import { type IR } from "./ir.ts";

export type Env = Record<string, unknown>;
export type Closure = (env: Env) => unknown;
export type ProgramClosure = (env: Env) => ($: unknown) => Promise<unknown>;

export interface EmitOps {
  string: (ir: IR) => string;
  programString: (ir: IR) => string;
  programClosure: (ir: IR) => ProgramClosure;
}

// === Emit to String ===

export function emitString(node: IR): string {
  switch (node.tag) {
    case 'literal':
      return JSON.stringify(node.value);

    case 'var':
      return node.name;

    case 'call': {
      const fn = emitString(node.fn);
      const args = node.args.map(a =>
        a.tag === 'spread' ? \`...\${emitString(a.value)}\` : emitString(a)
      ).join(', ');
      return \`\${fn}(\${args})\`;
    }

    case 'member':
      return \`\${emitString(node.obj)}.\${node.field}\`;

    case 'index':
      return \`\${emitString(node.obj)}[\${emitString(node.key)}]\`;

    case 'arrow': {
      const params = node.params.join(', ');
      const body = emitString(node.body);
      return node.params.length === 1
        ? \`(\${params}) => \${body}\`
        : \`(\${params}) => \${body}\`;
    }

    case 'function': {
      const params = node.params.join(', ');
      const body = emitString(node.body);
      return \`function(\${params}) { return \${body}; }\`;
    }

    case 'object': {
      const props = node.properties.map(p =>
        \`[\${JSON.stringify(p.key)}]: \${emitString(p.value)}\`
      ).join(', ');
      return \`{ \${props} }\`;
    }

    case 'array': {
      const elems = node.elements.map(e =>
        e.tag === 'spread' ? \`...\${emitString(e.value)}\` : emitString(e)
      ).join(', ');
      return \`[\${elems}]\`;
    }

    case 'spread':
      return \`...\${emitString(node.value)}\`;

    case 'ternary':
      return \`(\${emitString(node.cond)} ? \${emitString(node.then)} : \${emitString(node.else)})\`;

    case 'seq':
      return \`(\${emitString(node.first)}, \${emitString(node.rest)})\`;
  }
}

// === Emit to Closure ===

export function emitClosure(node: IR): Closure {
  switch (node.tag) {
    case 'literal':
      return (_env) => node.value;

    case 'var':
      return (env) => env[node.name];

    case 'call': {
      const fnClosure = emitClosure(node.fn);
      const argClosures = node.args.map(a => {
        if (a.tag === 'spread') {
          const inner = emitClosure(a.value);
          return { spread: true, fn: inner };
        }
        return { spread: false, fn: emitClosure(a) };
      });

      return (env) => {
        const fn = fnClosure(env) as Function;
        const args: unknown[] = [];
        for (const arg of argClosures) {
          if (arg.spread) {
            const spreadVal = arg.fn(env);
            if (Array.isArray(spreadVal)) {
              args.push(...spreadVal);
            }
          } else {
            args.push(arg.fn(env));
          }
        }
        return fn(...args);
      };
    }

    case 'member': {
      const objClosure = emitClosure(node.obj);
      return (env) => (objClosure(env) as any)[node.field];
    }

    case 'index': {
      const objClosure = emitClosure(node.obj);
      const keyClosure = emitClosure(node.key);
      return (env) => (objClosure(env) as any)[keyClosure(env) as any];
    }

    case 'arrow': {
      const bodyClosure = emitClosure(node.body);
      return (env) => (...args: unknown[]) => {
        const innerEnv = { ...env };
        node.params.forEach((p, i) => { innerEnv[p] = args[i]; });
        return bodyClosure(innerEnv);
      };
    }

    case 'function': {
      const bodyClosure = emitClosure(node.body);
      return (env) => function (this: unknown, ...args: unknown[]) {
        const innerEnv: Env = { ...env, this: this };
        node.params.forEach((p, i) => { innerEnv[p] = args[i]; });
        return bodyClosure(innerEnv);
      };
    }

    case 'object': {
      const propClosures = node.properties.map(p => ({
        key: p.key,
        valueClosure: emitClosure(p.value)
      }));
      return (env) => {
        const obj: Record<string, unknown> = {};
        for (const { key, valueClosure } of propClosures) {
          obj[key] = valueClosure(env);
        }
        return obj;
      };
    }

    case 'array': {
      const elemClosures = node.elements.map(e => {
        if (e.tag === 'spread') {
          const inner = emitClosure(e.value);
          return { spread: true, fn: inner };
        }
        return { spread: false, fn: emitClosure(e) };
      });

      return (env) => {
        const arr: unknown[] = [];
        for (const elem of elemClosures) {
          if (elem.spread) {
            const spreadVal = elem.fn(env);
            if (Array.isArray(spreadVal)) {
              arr.push(...spreadVal);
            }
          } else {
            arr.push(elem.fn(env));
          }
        }
        return arr;
      };
    }

    case 'spread':
      // Spread is handled in call/array contexts
      throw new Error('spread must be used in call or array context');

    case 'ternary': {
      const condClosure = emitClosure(node.cond);
      const thenClosure = emitClosure(node.then);
      const elseClosure = emitClosure(node.else);
      return (env) => condClosure(env) ? thenClosure(env) : elseClosure(env);
    }

    case 'seq': {
      const firstClosure = emitClosure(node.first);
      const restClosure = emitClosure(node.rest);
      return (env) => {
        firstClosure(env);
        return restClosure(env);
      };
    }
  }
}

// === Program wrapper ===

export function emitProgramString(body: IR): string {
  return \`export default async ($) => {
  let $env = $.env();
  return \${emitString(body)};
};\`;
}

export function emitProgramClosure(body: IR): (env: Env) => ($: unknown) => Promise<unknown> {
  const bodyClosure = emitClosure(body);
  return (env) => async ($: unknown) => {
    // Create initial $env from interpreter
    const $env = ($ as any).env();
    return bodyClosure({ ...env, $, $env });
  };
}

export function build$emit($: EmitOps): void {
  $.string = emitString;
  $.programString = emitProgramString;
  $.programClosure = emitProgramClosure;
};
`,
  'empty.ts': `/**
 * Empty language - the minimal foundation for extensions.
 *
 * Does nothing useful, but doesn't error either.
 * Running a file with --no-core produces undefined.
 */

import type { Extension } from './extension.ts';
import { ir } from './ir.ts';

export const emptyExtension: Extension = {
  name: 'empty',
  description: 'Empty language - does nothing',

  $pre: ($) => {
    $.read = () => '';
  },

  $parse: ($) => {
    $.program = () => (_input, pos) => ({ ok: true, value: undefined as any, pos });
  },

  $compile: ($) => {
    $.compileProgram = () => ir.lit(undefined);
    $.ir = ir;
  },

  $emit: ($) => {
    $.programString = () => 'export default async ($) => undefined;';
    $.programClosure = () => () => async () => undefined;
  },

  $post: ($) => {
    $.write = () => {};
  },
};

export default emptyExtension;
`,
  'extension.ts': `// Extensions for next-gen Unsound
//
// An extension is an object with optional $parse, $compile, $emit, $interpret keys.
// Each is a builder function that takes the base implementation and returns an extended one.
//
// Extensions can include metadata:
//   name: string        - Must match file basename (e.g., "meso" for meso.us)
//   description: string - Human-readable description
//   requires: string[]  - Names of required extensions (must be loaded first)
//   version: string     - Semantic version

import { existsSync, readFileSync, writeFileSync, statSync } from 'fs';
import { join, basename, dirname, resolve } from 'path';
import { ParseError, formatParseError, type ParserOps } from "./parse.ts";
import type { CompilerOps } from './compile.ts';
import { createInterpret, type InterpretOps, type Env } from './interpret.ts';
import { type AnalyzeOps } from './analyze.ts';
import { PreOps } from './pre.ts';
import { EmitOps } from './emit.ts';
import { PostOps } from './post.ts';
import { emptyExtension } from './empty.ts';

// Re-export types for convenience
export type { InterpretOps, Env, PreOps, PostOps, EmitOps, AnalyzeOps, ParserOps, CompilerOps };

// Extension metadata
export interface ExtensionMeta {
  name: string;
  description?: string;
  requires?: string | string[];  // Single string or array (for .us files without array syntax)
  version?: string;
}

// Extension type - each key is optional
// All phases use mutation style (mutate the ops object, return void)
export interface Extension extends Partial<ExtensionMeta> {
  $pre?: ($: PreOps) => void;
  $parse?: ($: ParserOps) => void;
  $compile?: ($: CompilerOps) => void;
  $analyze?: ($: AnalyzeOps) => void;
  $emit?: ($: EmitOps) => void;
  $post?: ($: PostOps) => void;
  $interpret?: ($: InterpretOps) => void;

  // Additional interpreters, compilers, etc. (e.g., $type for type checking)
  // Note: index signature must be compatible with all specific properties
  [key: \`$\${string}\`]: (($: any) => void) | undefined;
}

// A Language is the result of composing extensions
// Supports multiple interpreters via dynamic keys
export interface Language {
  $pre: PreOps;
  $parse: ParserOps;
  $compile: CompilerOps;
  $analyze: AnalyzeOps;
  $emit: EmitOps;
  $post: PostOps;
  $interpret: InterpretOps;
  // Track loaded extension names for dependency checking
  _loadedExtensions: Set<string>;
  // Additional interpreters/phases
  [key: \`$\${string}\`]: InterpretOps | ParserOps | CompilerOps | AnalyzeOps | EmitOps | PreOps | PostOps | undefined;
}

// Default extension search paths (relative to cwd)
const DEFAULT_SEARCH_PATHS = [
  'extensions',
  '.',
];

// Add cross-references: every phase can access every other phase via $.<phaseName>
function attachCrossReferences(lang: Language): void {
  const keys = Object.keys(lang).filter(k => k.startsWith('$'));
  for (const phase of keys) {
    for (const other of keys) {
      (lang[phase as keyof Language] as any)[other] = lang[other as keyof Language];
    }
  }
}

// Resolve an extension name to a file path
// Searches: exact path, then search paths with .us, .ts, .js extensions (in order)
export function resolveExtension(name: string, searchPaths: string[] = DEFAULT_SEARCH_PATHS): string | null {
  // If it's already a full path that exists, use it
  if (existsSync(name)) {
    return name;
  }

  // Try adding extensions (prefer .us, then .ts, then .js)
  for (const ext of ['.us', '.ts', '.js']) {
    if (existsSync(name + ext)) {
      return name + ext;
    }
  }

  // Search in search paths
  for (const searchPath of searchPaths) {
    for (const ext of ['', '.us', '.ts', '.js']) {
      const fullPath = join(searchPath, name + ext);
      if (existsSync(fullPath)) {
        return fullPath;
      }
    }
  }

  return null;
}

// Extract extension name from file path
export function extensionNameFromPath(filePath: string): string {
  const base = basename(filePath);
  // Remove .us, .ts, or .js extension
  return base.replace(/\\.(us|ts|js)$/, '');
}

// Parse the //usc directive from source to get default extensions
// Format: //usc -x meso -x const
export function parseDefaultExtensions(source: string): string[] {
  const match = source.match(/^\\/\\/usc\\s+(.+)$/m);
  if (!match) return [];

  const args = match[1].trim();
  const extensions: string[] = [];
  const parts = args.split(/\\s+/);

  for (let i = 0; i < parts.length; i++) {
    if (parts[i] === '-x' && i + 1 < parts.length) {
      extensions.push(parts[i + 1]);
      i++;
    }
  }

  return extensions;
}

// Check that an extension's requirements are satisfied
// Accepts requires as string or string[] for flexibility
function checkRequirements(ext: Extension, loadedExtensions: Set<string>, extPath: string): void {
  if (!ext.requires) return;

  // Normalize to array (accept single string for .us files without array syntax)
  const requires = typeof ext.requires === 'string' ? [ext.requires] : ext.requires;
  if (requires.length === 0) return;

  const missing = requires.filter(req => !loadedExtensions.has(req));
  if (missing.length > 0) {
    const extName = ext.name || extensionNameFromPath(extPath);
    throw new Error(
      \`Extension "\${extName}" requires [\${missing.join(', ')}] but they are not loaded. \` +
      \`Loaded extensions: [\${[...loadedExtensions].join(', ')}]\`
    );
  }
}

// Validate extension name matches file basename
function validateExtensionName(ext: Extension, filePath: string): void {
  if (!ext.name) return; // No name specified, skip validation

  const expectedName = extensionNameFromPath(filePath);
  if (ext.name !== expectedName) {
    throw new Error(
      \`Extension name "\${ext.name}" does not match file basename "\${expectedName}" \` +
      \`(from \${filePath})\`
    );
  }
}

// Apply a single extension to a language
// All extensions mutate in place
export function applyExtension(lang: Language, ext: Extension, filePath?: string): Language {
  // Validate and check requirements
  if (filePath) {
    validateExtensionName(ext, filePath);
  }
  checkRequirements(ext, lang._loadedExtensions, filePath || 'unknown');

  // Apply phase extensions in pipeline order: pre, parse, compile, emit, post
  if (ext.$pre) {
    ext.$pre(lang.$pre);
  }
  if (ext.$parse) {
    ext.$parse(lang.$parse);
  }
  if (ext.$compile) {
    ext.$compile(lang.$compile);
  }
  if (ext.$emit) {
    ext.$emit(lang.$emit);
  }
  if (ext.$post) {
    ext.$post(lang.$post);
  }

  // Apply $analyze if present
  if (ext.$analyze) {
    ext.$analyze(lang.$analyze);
  }

  // Apply all interpreter extensions (any key starting with $ that's not a core phase)
  const corePhases = ['$pre', '$parse', '$compile', '$analyze', '$emit', '$post'];
  for (const key of Object.keys(ext)) {
    if (key.startsWith('$') && !corePhases.includes(key)) {
      const builder = ext[key as keyof Extension] as (($: InterpretOps) => void) | undefined;
      if (builder) {
        // Create interpreter if it doesn't exist yet
        if (!lang[key as keyof Language]) {
          (lang as any)[key] = createInterpret();
        }
        builder(lang[key as keyof Language] as InterpretOps);
      }
    }
  }

  // Track loaded extension
  const extName = ext.name || (filePath ? extensionNameFromPath(filePath) : undefined);
  if (extName) {
    lang._loadedExtensions.add(extName);
  }

  // Re-attach cross-references after any new phases are added
  attachCrossReferences(lang);

  return lang;
}

// Create a language from a list of extensions
// Always starts with the empty extension which provides stub implementations
export function createLanguage(extensions: Extension[] = []): Language {
  // Start with empty ops
  const base: Language = {
    $pre: {} as PreOps,
    $parse: {} as ParserOps,
    $compile: {} as CompilerOps,
    $analyze: {} as AnalyzeOps,
    $emit: {} as EmitOps,
    $post: {} as PostOps,
    $interpret: {} as InterpretOps,
    _loadedExtensions: new Set(),
  };

  // Set up cross-references so every phase can access every other
  attachCrossReferences(base);

  // Apply empty extension first to provide stub implementations
  applyExtension(base, emptyExtension);

  return extensions.reduce((lang, ext) => applyExtension(lang, ext), base);
}

// Load a TypeScript extension
async function loadTsExtension(extPath: string): Promise<Extension> {
  const absPath = resolve(extPath);
  const mod = await import(absPath);
  if (mod.default && typeof mod.default === 'object') return mod.default;
  if (mod.extension && typeof mod.extension === 'object') return mod.extension;
  if (mod.fullExtension && typeof mod.fullExtension === 'object') return mod.fullExtension;
  if (mod.$parse || mod.$compile || mod.$emit || mod.$interpret) return mod;
  throw new Error(\`Could not find extension in \${extPath}\`);
}

// Load a .us extension by compiling it with its //usc dependencies
// Caches compiled .us.js based on mtime
// Core is always loaded first (unless the extension itself is core)
async function loadUsExtension(extPath: string, _lang: Language): Promise<Extension> {
  const absPath = resolve(extPath);
  const cachedPath = absPath + '.js';

  // Check if cached version exists and is newer than source
  if (existsSync(cachedPath)) {
    const srcStat = statSync(absPath);
    const cacheStat = statSync(cachedPath);
    if (cacheStat.mtimeMs > srcStat.mtimeMs) {
      // Use cached version
      return loadTsExtension(cachedPath);
    }
  }

  // Need to compile - read source and get its //usc directive
  const source = readFileSync(absPath, 'utf-8');
  const uscExtensions = parseDefaultExtensions(source);

  const verbose = process.env.USC_VERBOSE === '1';
  const log = verbose ? (msg: string) => console.error(\`usc: \${msg}\`) : () => { };

  log(\`compiling \${basename(absPath)} (requires: \${uscExtensions.join(', ') || 'none'})\`);

  // Build a language for compiling this extension
  // Always start with core (provides parser, compiler, etc.)
  const compileLang = createLanguage([]);
  await loadExtension('core', compileLang);

  // Load the //usc extensions (may recursively compile other .us files)
  for (const extName of uscExtensions) {
    log(\`  loading dependency \${extName} for \${basename(absPath)}\`);
    await loadExtension(extName, compileLang);
  }

  log(\`  parsing \${basename(absPath)}\`);
  // Debug: binary search for parse failure
  if (verbose) {
    const lines = source.split('\\n');
    let lo = 0, hi = lines.length;
    while (lo < hi) {
      const mid = Math.floor((lo + hi) / 2);
      const partial = lines.slice(0, mid + 1).join('\\n');
      const result = compileLang.$parse.program()(partial, 0);
      if (result.ok) {
        lo = mid + 1;
      } else {
        hi = mid;
      }
    }
    log(\`  first failing line: \${lo + 1}\`);
    if (lo < lines.length) {
      log(\`  line content: \${lines[lo]}\`);
    }
  }
  // Compile to JS
  const js = compileUsToJs(compileLang, source, absPath, uscExtensions);
  log(\`  compiled \${basename(absPath)}\`);

  // Write cache
  writeFileSync(cachedPath, js);

  // Load the compiled version
  return loadTsExtension(cachedPath);
}

// Compile a .us extension source to a JS module
function compileUsToJs(lang: Language, source: string, absPath: string, uscExtensions: string[]): string {
  const parseResult = lang.$parse.program()(source, 0);
  if (!parseResult.ok) {
    const formatted = formatParseError(source, parseResult.pos, parseResult.expected);
    throw new Error(\`Parse error in \${basename(absPath)}:\\n\${formatted}\`);
  }

  const ir = lang.$compile.compileProgram(parseResult.value);
  const programJs = lang.$emit.programString(ir);

  // Generate extension loading code (core is always loaded first)
  const extLoads = uscExtensions.map(name => \`await loadExtension('\${name}', lang);\`);

  return \`// Compiled from \${basename(absPath)}
import { createLanguage, loadExtension } from '\${resolve(import.meta.dirname, 'extension.ts')}';

const lang = createLanguage([]);
await loadExtension('core', lang);
\${extLoads.join('\\n')}

const program = \${programJs.replace('export default ', '').replace(/;$/, '')};
const result = await program(lang.$interpret);

export default result;
\`;
}

// Load and apply an extension by name or path
export async function loadExtension(
  nameOrPath: string,
  lang: Language,
  searchPaths: string[] = DEFAULT_SEARCH_PATHS
): Promise<Extension> {
  const resolvedPath = resolveExtension(nameOrPath, searchPaths);
  if (!resolvedPath) {
    throw new Error(\`Extension not found: \${nameOrPath} (searched: \${searchPaths.join(', ')})\`);
  }

  const ext = resolvedPath.endsWith('.us')
    ? await loadUsExtension(resolvedPath, lang)
    : await loadTsExtension(resolvedPath);

  applyExtension(lang, ext, resolvedPath);
  return ext;
}

// Load multiple extensions by name
export async function loadExtensions(
  names: string[],
  lang: Language,
  searchPaths: string[] = DEFAULT_SEARCH_PATHS
): Promise<void> {
  for (const name of names) {
    await loadExtension(name, lang, searchPaths);
  }
}

// Convenience: run source through the full pipeline
export async function run(lang: Language, source: string, interpretKey: string = 'interpret'): Promise<unknown> {
  const parseResult = lang.$parse.program()(source, 0);
  if (!parseResult.ok) {
    const formatted = formatParseError(source, parseResult.pos, parseResult.expected);
    throw new Error(\`Parse error:\\n\${formatted}\`);
  }

  const interpreter = lang[\`$\${interpretKey}\` as keyof Language] as InterpretOps | undefined;
  if (!interpreter) {
    throw new Error(\`No interpreter found for key: \${interpretKey}\`);
  }

  const ir = lang.$compile.compileProgram(parseResult.value);
  const closure = lang.$emit.programClosure(ir)({});
  return await (closure as Function)(interpreter);
}

// Convenience: compile source to JS string
export function compileToJS(lang: Language, source: string): string {
  const parseResult = lang.$parse.program()(source, 0);
  if (!parseResult.ok) {
    const formatted = formatParseError(source, parseResult.pos, parseResult.expected);
    throw new Error(\`Parse error:\\n\${formatted}\`);
  }

  const ir = lang.$compile.compileProgram(parseResult.value);
  return lang.$emit.programString(ir);
}
`,
  'interpret.ts': `// Generic interpreter infrastructure
// Provides types and base implementation that can be extended
//
// Key design: env is an opaque lexically-scoped value passed explicitly.
// The compiler threads env through; interpreters decide what env contains.

// Environment interface - what operations can be done on env
// Different interpreters can provide different implementations
export interface Env {
  lookup(name: string): unknown;
  extend(bindings: Record<string, unknown>): Env;  // Create child env
  bind(name: string, value: unknown): void;        // Mutate current frame (for letrec)
  mutate(name: string, value: unknown): void;      // Mutate existing binding (for assignment)
  markConst(name: string): void;                   // Mark binding as const (for const.us)
  isConst(name: string): boolean;                  // Check if binding is const
}

// Interpreter operations - what $ provides at runtime
// Operations that need $env take it as first parameter
export interface InterpretOps {
  // Environment factory
  env: () => Env;

  // Literals (no $env needed)
  number: (n: number) => unknown;
  string: (s: string) => unknown;
  boolean: (b: boolean) => unknown;

  // Bindings ($env passed explicitly)
  lookup: ($env: Env, name: string) => unknown;
  let: ($env: Env, name: string, valueFn: ($env: Env) => unknown, bodyFn: ($env: Env) => unknown) => unknown;
  // assign is provided by meso extension, not base

  // Functions ($env passed explicitly for closure capture)
  lambda: ($env: Env, params: string[], bodyFn: ($env: Env) => unknown) => unknown;
  call: (fn: unknown, args: unknown[]) => unknown;

  // Control ($env passed to thunks)
  if: (cond: unknown, thenFn: ($env: Env) => unknown, elseFn: ($env: Env) => unknown, $env: Env) => unknown;

  // Objects (no $env needed)
  object: (properties: Record<string, unknown>) => unknown;
  index: (obj: unknown, key: unknown) => unknown;
  setIndex: (obj: unknown, key: unknown, value: unknown) => unknown;

  // Extensions can add more operations
  [key: string]: unknown;
}

// Create a prototype-chain based environment
// Uses Object.create for efficient inheritance
// Tracks const bindings in a separate set that inherits via prototype
export function createEnv(initial: Record<string, unknown> = {}): Env {
  const frame = { ...initial };
  const consts: Record<string, boolean> = {};

  return createEnvFromFrame(frame, consts);
}

// Helper to create env from existing frame (for extend)
function createEnvFromFrame(frame: Record<string, unknown>, consts: Record<string, boolean>): Env {
  return {
    lookup(name: string): unknown {
      return frame[name];
    },
    extend(bindings: Record<string, unknown>): Env {
      // Child inherits from this frame and consts via prototype
      const childFrame = Object.create(frame);
      Object.assign(childFrame, bindings);
      const childConsts = Object.create(consts);
      return createEnvFromFrame(childFrame, childConsts);
    },
    bind(name: string, value: unknown): void {
      frame[name] = value;
    },
    mutate(name: string, value: unknown): void {
      // Walk prototype chain to find and update existing binding
      let obj: Record<string, unknown> | null = frame;
      while (obj !== null) {
        if (Object.hasOwn(obj, name)) {
          obj[name] = value;
          return;
        }
        obj = Object.getPrototypeOf(obj);
      }
      throw new Error(\`Cannot assign to undefined variable: \${name}\`);
    },
    markConst(name: string): void {
      consts[name] = true;
    },
    isConst(name: string): boolean {
      return consts[name] === true;
    },
  };
}

// Primitive operator methods
const numberOps = (n: number): Record<string, unknown> => ({
  'op+': (other: unknown) => n + (other as number),
  'op-': (other: unknown) => n - (other as number),
  'op*': (other: unknown) => n * (other as number),
  'op/': (other: unknown) => n / (other as number),
  'op%': (other: unknown) => n % (other as number),
  'op<': (other: unknown) => n < (other as number),
  'op>': (other: unknown) => n > (other as number),
  'op<=': (other: unknown) => n <= (other as number),
  'op>=': (other: unknown) => n >= (other as number),
  'op==': (other: unknown) => n === other,
  'op!=': (other: unknown) => n !== other,
  'opNeg': () => -n,
});

const stringOps = (s: string): Record<string, unknown> => ({
  'op+': (other: unknown) => s + (other as string),
  'op==': (other: unknown) => s === other,
  'op!=': (other: unknown) => s !== other,
  'op<': (other: unknown) => s < (other as string),
  'op>': (other: unknown) => s > (other as string),
  'op<=': (other: unknown) => s <= (other as string),
  'op>=': (other: unknown) => s >= (other as string),
});

const booleanOps = (b: boolean): Record<string, unknown> => ({
  'op!': () => !b,
  'op==': (other: unknown) => b === other,
  'op!=': (other: unknown) => b !== other,
  'op&&': (other: unknown) => b && (other as boolean),
  'op||': (other: unknown) => b || (other as boolean),
});

// Access field on primitive: check ops first, then proxy to underlying with binding
function primitiveMember(obj: unknown, ops: Record<string, unknown>, field: string): unknown {
  if (field in ops) return ops[field];
  const value = (obj as any)[field];
  if (typeof value === 'function') return value.bind(obj);
  return value;
}

// Base interpreter builder - mutation style
// Extensions mutate $ to override methods
export function build$interpret($: InterpretOps, globals: Record<string, unknown> = {}): void {
  // Environment factory - creates initial env with globals
  $.env = () => createEnv(globals);

  $.number = (n) => n;
  $.string = (s) => s;
  $.boolean = (b) => b;
  $.null = () => null;

  $.lookup = ($env, name) => $env.lookup(name);

  $.let = ($env, name, valueFn, bodyFn) => {
    // Create child $env with name pre-bound to undefined (letrec semantics)
    const child = $env.extend({ [name]: undefined });
    // Evaluate value in child so recursive refs work
    const value = valueFn(child);
    // Update the binding
    child.bind(name, value);
    // Evaluate body in child
    return bodyFn(child);
  };

  // $.assign is provided by meso extension, not base

  $.lambda = ($env, params, bodyFn) => {
    // $env is captured via JS closure - lexical scoping!
    return (...args: unknown[]) => {
      const bindings: Record<string, unknown> = {};
      params.forEach((p, i) => { bindings[p] = args[i]; });
      // Create child of captured $env with param bindings
      const child = $env.extend(bindings);
      return bodyFn(child);
    };
  };

  $.call = (fn, args) => (fn as Function)(...args);

  // Strict equality - works on any values including null/undefined.
  // We can't compile \`a === b\` as e.g. \`a['op==='](b)\` because both \`a\` and \`b\`
  // could be null/undefined.
  $.strictEq = (a: unknown, b: unknown) => a === b;
  $.strictNeq = (a: unknown, b: unknown) => a !== b;

  $.if = (cond, thenFn, elseFn, $env) => cond ? thenFn($env) : elseFn($env);

  $.object = (o) => o;

  $.array = (arr: any[]) => arr;

  $.index = (obj, key) => {
    const k = key as string;
    if (typeof obj === 'number') {
      return primitiveMember(obj, numberOps(obj), k);
    }
    if (typeof obj === 'string') {
      return primitiveMember(obj, stringOps(obj), k);
    }
    if (typeof obj === 'boolean') {
      return primitiveMember(obj, booleanOps(obj), k);
    }
    // Objects and arrays: bind methods to preserve 'this'
    const value = (obj as Record<string, unknown>)[k];
    if (typeof value === 'function') {
      return (value as Function).bind(obj);
    }
    return value;
  };

  $.setIndex = (obj, key, value) => {
    (obj as Record<string, unknown>)[key as string] = value;
    return value;
  };
}

// $operators object - provides operator functions for use in Unsound code
export const $operators: Record<string, (...args: unknown[]) => unknown> = {
  'op===': (a, b) => a === b,
  'op!==': (a, b) => a !== b,
  'op==': (a, b) => a == b,
  'op!=': (a, b) => a != b,
  'op<': (a, b) => (a as number) < (b as number),
  'op>': (a, b) => (a as number) > (b as number),
  'op<=': (a, b) => (a as number) <= (b as number),
  'op>=': (a, b) => (a as number) >= (b as number),
  'op+': (a, b) => (a as number) + (b as number),
  'op-': (a, b) => (a as number) - (b as number),
  'op*': (a, b) => (a as number) * (b as number),
  'op/': (a, b) => (a as number) / (b as number),
  'op%': (a, b) => (a as number) % (b as number),
  'op&&': (a, b) => a && b,
  'op||': (a, b) => a || b,
  'op!': (a) => !a,
  'opNeg': (a) => -(a as number),
};

// Default global environment
export const defaultEnv: Record<string, unknown> = {
  $operators,
};

// Convenience: create interpreter with default globals
export function createInterpret(globals: Record<string, unknown> = {}): InterpretOps {
  const $ = {} as InterpretOps;
  build$interpret($, { ...defaultEnv, ...globals });
  return $;
}
`,
  'ir.ts': `/**
 * IR
 *
 * Represents the core format for communication between the compiler and emitter.
 */

/**
 * The type of IR expressions.
 */
export type IR =
  | { tag: 'literal'; value: number | string | boolean | null | undefined }
  | { tag: 'var'; name: string }
  | { tag: 'call'; fn: IR; args: IR[] }
  | { tag: 'member'; obj: IR; field: string }
  | { tag: 'index'; obj: IR; key: IR }
  | { tag: 'arrow'; params: string[]; body: IR }
  | { tag: 'function'; params: string[]; body: IR }
  | { tag: 'object'; properties: { key: string; value: IR }[] }
  | { tag: 'array'; elements: IR[] }
  | { tag: 'spread'; value: IR }
  | { tag: 'ternary'; cond: IR; then: IR; else: IR }
  | { tag: 'seq'; first: IR; rest: IR };

/**
 * IR constructors and helpers.
 */
export const ir = {
  lit: (value: number | string | boolean | null | undefined): IR =>
    ({ tag: 'literal', value }),

  // Convenience aliases for Unsound extensions
  string: (s: string): IR => ({ tag: 'literal', value: s }),
  number: (n: number): IR => ({ tag: 'literal', value: n }),

  var: (name: string): IR =>
    ({ tag: 'var', name }),

  // Variadic call - works from Unsound without needing JS arrays
  call: (fn: IR, ...args: IR[]): IR =>
    ({ tag: 'call', fn, args }),

  member: (obj: IR, field: string): IR =>
    ({ tag: 'member', obj, field }),

  index: (obj: IR, key: IR): IR =>
    ({ tag: 'index', obj, key }),

  arrow: (params: string[], body: IR): IR =>
    ({ tag: 'arrow', params, body }),

  // Single-param arrow - easier to call from Unsound
  arrow1: (param: string, body: IR): IR =>
    ({ tag: 'arrow', params: [param], body }),

  fn: (params: string[], body: IR): IR =>
    ({ tag: 'function', params, body }),

  object: (properties: { key: string; value: IR }[]): IR =>
    ({ tag: 'object', properties }),

  prop: (key: string, value: IR): { key: string; value: IR } =>
    ({ key, value }),

  // Variadic array - works from Unsound without needing JS arrays
  array: (...elements: IR[]): IR =>
    ({ tag: 'array', elements }),

  spread: (value: IR): IR =>
    ({ tag: 'spread', value }),

  ternary: (cond: IR, then_: IR, else_: IR): IR =>
    ({ tag: 'ternary', cond, then: then_, else: else_ }),

  // Sequence: evaluate first, then rest, return rest (compiles to comma operator)
  seq: (first: IR, rest: IR): IR =>
    ({ tag: 'seq', first, rest }),

  // Helper for $.method(...args) pattern
  $: (method: string, ...args: IR[]): IR =>
    ir.call(ir.member(ir.var('$'), method), ...args),
};
`,
  'parse.ts': `/**
 * Core parser.
 */
import {
  type Expr,
  type LetExpr,
  type LambdaExpr,
  type IfExpr,
  type ObjectExpr,
  type ArrayExpr,
  type IndexExpr,
  type AssignIndex,
  type LiteralExpr,
  type IdentExpr,
  type Span,
  posToLineCol,
} from "./ast.ts";
import { fix } from "./util.ts";

export type ParseResult<T> =
  | { ok: true; value: T; pos: number }
  | { ok: false; expected: string; pos: number };

export type Parser<T> = (input: string, pos: number) => ParseResult<T>;

export interface ParserOps {
  // === Primitive combinators ===
  char: (c: string) => Parser<string>;
  satisfy: (pred: (c: string) => boolean, name: string) => Parser<string>;
  str: (s: string) => Parser<string>;
  eof: () => Parser<null>;

  // === Higher-order combinators ===
  seq: <T extends unknown[]>(...parsers: { [K in keyof T]: Parser<T[K]> }) => Parser<T>;
  alt: <T>(...parsers: Parser<T>[]) => Parser<T>;
  many: <T>(p: Parser<T>) => Parser<T[]>;
  many1: <T>(p: Parser<T>) => Parser<T[]>;
  map: <A, B>(p: Parser<A>, fn: (a: A, loc: Span) => B) => Parser<B>;
  opt: <T>(p: Parser<T>) => Parser<T | null>;
  lazy: <T>(fn: () => Parser<T>) => Parser<T>;
  sepBy: <T, S>(p: Parser<T>, sep: Parser<S>) => Parser<T[]>;
  sepBy1: <T, S>(p: Parser<T>, sep: Parser<S>) => Parser<T[]>;
  between: <A, B, C>(open: Parser<A>, p: Parser<B>, close: Parser<C>) => Parser<B>;

  // Location tracking: wrap parser to return { value, loc }
  withLoc: <T>(p: Parser<T>) => Parser<{ value: T; loc: Span }>;

  // === Whitespace and tokens ===
  whitespace: () => Parser<string>;
  ws: () => Parser<null>;  // Skip whitespace, return null
  token: (s: string) => Parser<string>;

  keywords: string[];  // List of keywords in the language; used with $.ident to stop matching keywords.
  keyword: (s: string) => Parser<string>;  // keyword that's not part of identifier

  // === Lexemes ===
  digit: () => Parser<string>;
  letter: () => Parser<string>;
  identChar: () => Parser<string>;
  numberLit: () => Parser<number>;
  stringLit: () => Parser<string>;
  ident: () => Parser<string>;

  // === Grammar rules (the extensible part) ===
  // Each rule is broken into small semantic pieces for extension overriding

  // Program structure
  program: () => Parser<Expr>;
  expr: () => Parser<Expr>;

  // Let expressions - broken into pieces
  letExpr: () => Parser<LetExpr>;
  letKeyword: () => Parser<string>;              // "let"
  letBinding: () => Parser<{ name: string; nameLoc: Span }>;  // the "x" in "let x = ..."
  letInitializer: () => Parser<Expr>;            // "= expr"
  letInKeyword: () => Parser<string>;            // "in"
  letBody: () => Parser<Expr>;                   // body expression

  // Lambda expressions - broken into pieces
  lambda: () => Parser<LambdaExpr>;
  lambdaParams: () => Parser<{ value: string; loc: Span }[]>;  // (x, y, z)
  lambdaParam: () => Parser<{ value: string; loc: Span }>;     // single param
  lambdaArrow: () => Parser<string>;             // "=>"
  lambdaBody: () => Parser<Expr>;                // body expression

  // If expressions - broken into pieces
  ifExpr: () => Parser<IfExpr>;
  ifKeyword: () => Parser<string>;               // "if"
  ifCondition: () => Parser<Expr>;               // condition expression
  thenKeyword: () => Parser<string>;             // "then"
  thenBranch: () => Parser<Expr>;                // then expression
  elseKeyword: () => Parser<string>;             // "else"
  elseBranch: () => Parser<Expr>;                // else expression

  // Application and access - broken into pieces
  appExpr: () => Parser<Expr>;
  callSuffix: () => Parser<Expr[]>;              // (args) - returns args
  memberName: () => Parser<string>;              // field name (allows keywords after .)
  memberSuffix: () => Parser<{ value: string; loc: Span }>;  // .field
  indexSuffix: () => Parser<Expr>;               // [key]

  // Assignment (SetIndex)
  assignExpr: () => Parser<Expr>;

  // Atoms
  atom: () => Parser<Expr>;
  objectExpr: () => Parser<ObjectExpr>;
  arrayExpr: () => Parser<ArrayExpr>;
  literal: () => Parser<LiteralExpr>;
  identExpr: () => Parser<IdentExpr>;

  // Object properties
  property: () => Parser<{ key: string; keyLoc?: Span; value: Expr }>;
  propertyKey: () => Parser<{ value: string; loc: Span }>;

  // Function args and params (legacy, for compatibility)
  params: () => Parser<{ value: string; loc: Span }[]>;
  args: () => Parser<Expr[]>;
}

export class ParseError extends Error {
  pos: number;
  expected: string;

  constructor(pos: number, expected: string) {
    super(\`Parse error at position \${pos}: expected \${expected}\`);
    this.name = 'ParseError';
    this.pos = pos;
    this.expected = expected;
  }

  // Format with source context
  format(source: string): string {
    return formatParseError(source, this.pos, this.expected);
  }
}

// Format a parse error with source context
export function formatParseError(
  source: string,
  pos: number,
  expected: string
): string {
  const { line, col } = posToLineCol(source, pos);
  const lines = source.split('\\n');

  // What did we actually find at this position?
  const found = pos >= source.length
    ? 'end of input'
    : source[pos] === '\\n'
      ? 'newline'
      : \`'\${source.slice(pos, pos + 20).split('\\n')[0]}\${source.length - pos > 20 ? '...' : ''}'\`;

  // Show context: 3 lines before and 2 lines after
  const contextBefore = 3;
  const contextAfter = 2;
  const startLine = Math.max(0, line - 1 - contextBefore);
  const endLine = Math.min(lines.length - 1, line - 1 + contextAfter);

  // Calculate line number width for alignment
  const maxLineNum = endLine + 1;
  const lineNumWidth = String(maxLineNum).length;

  const contextLines: string[] = [];
  for (let i = startLine; i <= endLine; i++) {
    const lineNum = String(i + 1).padStart(lineNumWidth, ' ');
    const marker = i === line - 1 ? '>' : ' ';
    contextLines.push(\`\${marker} \${lineNum} | \${lines[i]}\`);

    // Add caret line for the error line
    if (i === line - 1) {
      const padding = ' '.repeat(lineNumWidth + 4); // "  NN | "
      const caret = ' '.repeat(col - 1) + '^';
      contextLines.push(\`\${padding}\${caret}\`);
    }
  }

  return [
    \`Parse error at line \${line}, column \${col}\`,
    \`  expected: \${expected}\`,
    \`  found: \${found}\`,
    '',
    ...contextLines
  ].join('\\n');
}

// Base parser builder - mutates $ to add all parser operations
// All recursive calls go through $ for open recursion
export function build$parse($: ParserOps): void {
  // === Primitive combinators ===

  $.char = (c) => (input, pos) => {
    if (input[pos] === c) {
      return { ok: true, value: c, pos: pos + 1 };
    }
    return { ok: false, expected: \`'\${c}'\`, pos };
  };

  $.satisfy = (pred, name) => (input, pos) => {
    if (pos < input.length && pred(input[pos])) {
      return { ok: true, value: input[pos], pos: pos + 1 };
    }
    return { ok: false, expected: name, pos };
  };

  $.str = (s) => (input, pos) => {
    if (input.slice(pos, pos + s.length) === s) {
      return { ok: true, value: s, pos: pos + s.length };
    }
    return { ok: false, expected: \`"\${s}"\`, pos };
  };

  $.eof = () => (input, pos) => {
    if (pos >= input.length) {
      return { ok: true, value: null, pos };
    }
    return { ok: false, expected: "end of input", pos };
  };

  // === Higher-order combinators ===

  $.seq = (...parsers) => (input, pos) => {
    const results: unknown[] = [];
    let p = pos;
    for (const parser of parsers) {
      const r = parser(input, p);
      if (!r.ok) return r as ParseResult<any>;
      results.push(r.value);
      p = r.pos;
    }
    return { ok: true, value: results as any, pos: p };
  };

  $.alt = (...parsers) => (input, pos) => {
    let furthest: ParseResult<any> = {
      ok: false,
      expected: "alternative",
      pos,
    };
    for (const parser of parsers) {
      const r = parser(input, pos);
      if (r.ok) return r;
      if (r.pos > furthest.pos) furthest = r;
    }
    return furthest;
  };

  $.many = (p) => (input, pos) => {
    const results: any[] = [];
    let current = pos;
    while (true) {
      const r = p(input, current);
      if (!r.ok) break;
      results.push(r.value);
      current = r.pos;
    }
    return { ok: true, value: results, pos: current };
  };

  $.many1 = (p) => (input, pos) => {
    const first = p(input, pos);
    if (!first.ok) return first as ParseResult<any[]>;
    const rest = $.many(p)(input, first.pos);
    if (!rest.ok) return rest;
    return { ok: true, value: [first.value, ...rest.value], pos: rest.pos };
  };

  // Map with location: fn receives (value, loc) - loc can be ignored if not needed
  $.map = (p, fn) => (input, pos) => {
    const ws = $.ws()(input, pos);
    const start = ws.pos;
    const r = p(input, pos);
    if (!r.ok) return r as ParseResult<any>;
    return { ok: true, value: fn(r.value, { start, end: r.pos }), pos: r.pos };
  };

  $.opt = (p) => (input, pos) => {
    const r = p(input, pos);
    if (r.ok) return r;
    return { ok: true, value: null, pos };
  };

  $.lazy = (fn) => (input, pos) => fn()(input, pos);

  $.sepBy = (p, sep) => (input, pos) => {
    const first = p(input, pos);
    if (!first.ok) return { ok: true, value: [], pos };

    const results = [first.value];
    let current = first.pos;

    while (true) {
      const sepResult = sep(input, current);
      if (!sepResult.ok) break;
      const next = p(input, sepResult.pos);
      if (!next.ok) break;
      results.push(next.value);
      current = next.pos;
    }

    return { ok: true, value: results, pos: current };
  };

  $.sepBy1 = (p, sep) => (input, pos) => {
    const result = $.sepBy(p, sep)(input, pos);
    if (!result.ok) return result;
    if (result.value.length === 0) {
      return { ok: false, expected: "at least one element", pos };
    }
    return result;
  };

  $.between = (open, p, close) => (input, pos) => {
    const o = open(input, pos);
    if (!o.ok) return o as ParseResult<any>;
    const content = p(input, o.pos);
    if (!content.ok) return content;
    const c = close(input, content.pos);
    if (!c.ok) return c as ParseResult<any>;
    return { ok: true, value: content.value, pos: c.pos };
  };

  // Wrap a parser to return { value, loc } for capturing sub-part positions
  $.withLoc = (p) => (input, pos) => {
    const ws = $.ws()(input, pos);
    const start = ws.pos;
    const r = p(input, pos);
    if (!r.ok) return r as ParseResult<any>;
    return { ok: true, value: { value: r.value, loc: { start, end: r.pos } }, pos: r.pos };
  };

  // === Whitespace and tokens ===

  // Single whitespace character
  const wsChar = $.satisfy(
    (c) => c === " " || c === "\\n" || c === "\\t" || c === "\\r",
    "whitespace"
  );

  // Line comment: // ... until end of line
  const lineComment = () => (input: string, pos: number) => {
    if (input.slice(pos, pos + 2) !== '//') {
      return { ok: false, expected: "comment", pos };
    }
    let end = pos + 2;
    while (end < input.length && input[end] !== '\\n') {
      end++;
    }
    return { ok: true, value: "", pos: end };
  };

  // Block comment: /* ... */
  const blockComment = () => (input: string, pos: number) => {
    if (input.slice(pos, pos + 2) !== '/*') {
      return { ok: false, expected: "comment", pos };
    }
    let end = pos + 2;
    while (end < input.length - 1) {
      if (input.slice(end, end + 2) === '*/') {
        return { ok: true, value: "", pos: end + 2 };
      }
      end++;
    }
    return { ok: false, expected: "*/", pos: end };
  };

  $.whitespace = () => (input: string, pos: number) => {
    let current = pos;
    while (current < input.length) {
      // Try whitespace char
      const wsResult = wsChar(input, current);
      if (wsResult.ok) {
        current = wsResult.pos;
        continue;
      }
      // Try line comment
      const lineResult = lineComment()(input, current);
      if (lineResult.ok) {
        current = lineResult.pos;
        continue;
      }
      // Try block comment
      const blockResult = blockComment()(input, current);
      if (blockResult.ok) {
        current = blockResult.pos;
        continue;
      }
      break;
    }
    return { ok: true, value: "", pos: current };
  };

  // Note: can't use $.map here because $.map calls $.ws (would be circular)
  $.ws = () => (input, pos) => {
    const r = $.whitespace()(input, pos);
    return { ok: true, value: null, pos: r.pos };
  };

  $.token = (s) => (input, pos) => {
    const ws = $.ws()(input, pos);
    return $.str(s)(input, ws.pos);
  };

  $.keywords = ["let", "in", "if", "then", "else", "true", "false", "null"];

  $.keyword = (s) => (input, pos) => {
    const ws = $.ws()(input, pos);
    const kw = $.str(s)(input, ws.pos);
    if (!kw.ok) return kw;
    // Make sure keyword is not followed by identifier char
    if (kw.pos < input.length) {
      const next = input[kw.pos];
      if (
        (next >= "a" && next <= "z") ||
        (next >= "A" && next <= "Z") ||
        (next >= "0" && next <= "9") ||
        next === "_" ||
        next === "$"
      ) {
        return { ok: false, expected: \`keyword "\${s}"\`, pos: ws.pos };
      }
    }
    return kw;
  };

  // === Lexemes ===

  $.digit = () => $.satisfy((c) => c >= "0" && c <= "9", "digit");

  $.letter = () =>
    $.satisfy(
      (c) => (c >= "a" && c <= "z") || (c >= "A" && c <= "Z"),
      "letter"
    );

  $.identChar = () =>
    $.satisfy(
      (c) =>
        (c >= "a" && c <= "z") ||
        (c >= "A" && c <= "Z") ||
        (c >= "0" && c <= "9") ||
        c === "_" ||
        c === "$",
      "identifier character"
    );

  $.numberLit = () => (input, pos) => {
    const ws = $.ws()(input, pos);
    const digits = $.many1($.digit())(input, ws.pos);
    if (!digits.ok) return { ok: false, expected: "number", pos: ws.pos };
    return {
      ok: true,
      value: parseInt(digits.value.join(""), 10),
      pos: digits.pos,
    };
  };

  $.stringLit = () => (input, pos) => {
    const ws = $.ws()(input, pos);
    const open = $.char('"')(input, ws.pos);
    if (!open.ok) return { ok: false, expected: "string", pos: ws.pos };

    let current = open.pos;
    let value = "";

    while (current < input.length && input[current] !== '"') {
      if (input[current] === "\\\\" && current + 1 < input.length) {
        const next = input[current + 1];
        switch (next) {
          case "n":
            value += "\\n";
            break;
          case "t":
            value += "\\t";
            break;
          case "r":
            value += "\\r";
            break;
          case "\\\\":
            value += "\\\\";
            break;
          case '"':
            value += '"';
            break;
          default:
            value += next;
        }
        current += 2;
      } else {
        value += input[current];
        current++;
      }
    }

    if (current >= input.length) {
      return { ok: false, expected: 'closing "', pos: current };
    }

    return { ok: true, value, pos: current + 1 }; // Skip closing "
  };

  $.ident = () => (input, pos): ParseResult<string> => {
    const ws = $.ws()(input, pos);
    const first = $.alt($.letter(), $.char("_"), $.char("$"))(input, ws.pos);
    if (!first.ok) return { ok: false, expected: "identifier", pos: ws.pos };

    const rest = $.many($.identChar())(input, first.pos);

    // many() always succeeds, so we can safely access value
    const name =
      first.value +
      (rest as { ok: true; value: string[]; pos: number }).value.join("");
    const endPos = rest.pos;

    if ($.keywords.indexOf(name) !== -1) {
      return {
        ok: false,
        expected: "identifier (not a keyword)",
        pos: ws.pos,
      };
    }

    return { ok: true, value: name, pos: endPos };
  };

  // === Grammar rules ===

  $.program = () => (input, pos) => {
    const e = $.expr()(input, pos);
    if (!e.ok) return e;
    const end = $.seq($.ws(), $.eof())(input, e.pos);
    if (!end.ok) return end as ParseResult<any>;
    return e;
  };

  $.expr = () =>
    $.alt(
      $.lazy(() => $.letExpr()),
      $.lazy(() => $.lambda()),
      $.lazy(() => $.ifExpr()),
      $.lazy(() => $.assignExpr())
    );

  // Assignment: index = expr (low precedence, right-associative)
  $.assignExpr = () => (input, pos) => {
    // Skip whitespace to get true start for location tracking
    const wsStart = $.ws()(input, pos);
    const start = wsStart.pos;

    const left = $.appExpr()(input, pos);
    if (!left.ok) return left;

    // Check for = but not == (to avoid conflict with equality operator)
    const ws = $.ws()(input, left.pos);
    if (input[ws.pos] === '=' && input[ws.pos + 1] !== '=' && left.value.type === 'Index') {
      const value = $.expr()(input, ws.pos + 1);
      if (!value.ok) return value;
      return {
        ok: true,
        value: {
          type: 'SetIndex',
          object: (left.value as IndexExpr).object,
          key: (left.value as IndexExpr).key,
          value: value.value,
          loc: { start, end: value.pos },
        } as AssignIndex,
        pos: value.pos,
      };
    }

    return left;
  };

  // === Let expression pieces ===
  $.letKeyword = () => $.keyword("let");

  $.letBinding = () => $.map(
    $.withLoc($.ident()),
    (withLoc): { name: string; nameLoc: Span } => ({
      name: withLoc.value,
      nameLoc: withLoc.loc,
    })
  );

  $.letInitializer = () => (input, pos) => {
    const eq = $.token("=")(input, pos);
    if (!eq.ok) return eq as ParseResult<Expr>;
    return $.expr()(input, eq.pos);
  };

  $.letInKeyword = () => $.keyword("in");

  $.letBody = () => $.lazy(() => $.expr());

  $.letExpr = () => (input, pos) => {
    const ws = $.ws()(input, pos);
    const start = ws.pos;

    const kw = $.letKeyword()(input, pos);
    if (!kw.ok) return kw as ParseResult<LetExpr>;

    const binding = $.letBinding()(input, kw.pos);
    if (!binding.ok) return binding as ParseResult<LetExpr>;

    const value = $.letInitializer()(input, binding.pos);
    if (!value.ok) return value as ParseResult<LetExpr>;

    const inKw = $.letInKeyword()(input, value.pos);
    if (!inKw.ok) return inKw as ParseResult<LetExpr>;

    const body = $.letBody()(input, inKw.pos);
    if (!body.ok) return body as ParseResult<LetExpr>;

    return {
      ok: true,
      value: {
        type: "LetExpr",
        name: binding.value.name,
        nameLoc: binding.value.nameLoc,
        value: value.value,
        body: body.value,
        loc: { start, end: body.pos },
      },
      pos: body.pos,
    };
  };

  // === Lambda expression pieces ===
  $.lambdaParam = () => $.withLoc($.ident());

  $.lambdaParams = () => $.between(
    $.token("("),
    $.sepBy($.lazy(() => $.lambdaParam()), $.token(",")),
    $.token(")")
  );

  $.lambdaArrow = () => $.token("=>");

  $.lambdaBody = () => $.lazy(() => $.expr());

  $.lambda = () => (input, pos) => {
    const ws = $.ws()(input, pos);
    const start = ws.pos;

    const params = $.lambdaParams()(input, pos);
    if (!params.ok) return params as ParseResult<LambdaExpr>;

    const arrow = $.lambdaArrow()(input, params.pos);
    if (!arrow.ok) return arrow as ParseResult<LambdaExpr>;

    const body = $.lambdaBody()(input, arrow.pos);
    if (!body.ok) return body as ParseResult<LambdaExpr>;

    return {
      ok: true,
      value: {
        type: "Lambda",
        params: params.value.map(p => p.value),
        paramsLoc: params.value.map(p => p.loc),
        body: body.value,
        loc: { start, end: body.pos },
      },
      pos: body.pos,
    };
  };

  // === If expression pieces ===
  $.ifKeyword = () => $.keyword("if");

  $.ifCondition = () => $.lazy(() => $.expr());

  $.thenKeyword = () => $.keyword("then");

  $.thenBranch = () => $.lazy(() => $.expr());

  $.elseKeyword = () => $.keyword("else");

  $.elseBranch = () => $.lazy(() => $.expr());

  $.ifExpr = () => (input, pos) => {
    const ws = $.ws()(input, pos);
    const start = ws.pos;

    const ifKw = $.ifKeyword()(input, pos);
    if (!ifKw.ok) return ifKw as ParseResult<IfExpr>;

    const cond = $.ifCondition()(input, ifKw.pos);
    if (!cond.ok) return cond as ParseResult<IfExpr>;

    const thenKw = $.thenKeyword()(input, cond.pos);
    if (!thenKw.ok) return thenKw as ParseResult<IfExpr>;

    const thenExpr = $.thenBranch()(input, thenKw.pos);
    if (!thenExpr.ok) return thenExpr as ParseResult<IfExpr>;

    const elseKw = $.elseKeyword()(input, thenExpr.pos);
    if (!elseKw.ok) return elseKw as ParseResult<IfExpr>;

    const elseExpr = $.elseBranch()(input, elseKw.pos);
    if (!elseExpr.ok) return elseExpr as ParseResult<IfExpr>;

    return {
      ok: true,
      value: {
        type: "IfExpr",
        cond: cond.value,
        then: thenExpr.value,
        else: elseExpr.value,
        loc: { start, end: elseExpr.pos },
      },
      pos: elseExpr.pos,
    };
  };

  // === Application and access pieces ===
  $.callSuffix = () => $.between(
    $.token("("),
    $.lazy(() => $.args()),
    $.token(")")
  );

  // Member name allows identifiers OR keywords (e.g., obj.if is valid)
  $.memberName = () => (input, pos) => {
    const ws = $.ws()(input, pos);
    // Try identifier first
    const identResult = $.ident()(input, pos);
    if (identResult.ok) return identResult;
    // Try keywords - they're valid after a dot
    for (const kw of $.keywords) {
      const kwResult = $.str(kw)(input, ws.pos);
      if (kwResult.ok) {
        // Make sure it's not followed by identifier char (full keyword match)
        if (kwResult.pos < input.length) {
          const next = input[kwResult.pos];
          if ((next >= 'a' && next <= 'z') || (next >= 'A' && next <= 'Z') ||
              (next >= '0' && next <= '9') || next === '_' || next === '$') {
            continue; // Not a full keyword, try next
          }
        }
        return { ok: true, value: kw, pos: kwResult.pos };
      }
    }
    return { ok: false, expected: "member name", pos: ws.pos };
  };

  $.memberSuffix = () => (input, pos) => {
    const dot = $.token(".")(input, pos);
    if (!dot.ok) return dot as ParseResult<{ value: string; loc: Span }>;
    return $.withLoc($.memberName())(input, dot.pos);
  };

  $.indexSuffix = () => $.between(
    $.token("["),
    $.lazy(() => $.expr()),
    $.token("]")
  );

  // Application and index access - handles left recursion
  $.appExpr = () => (input, pos) => {
    // Skip whitespace to get true start for location tracking
    const ws = $.ws()(input, pos);
    const start = ws.pos;

    const atomResult = $.atom()(input, pos);
    if (!atomResult.ok) return atomResult;

    let current: ParseResult<Expr> = atomResult;

    while (true) {
      // Try function application: expr(args)
      const argsResult = $.callSuffix()(input, current.pos);

      if (argsResult.ok) {
        current = {
          ok: true,
          value: {
            type: "App",
            fn: current.value,
            args: argsResult.value,
            loc: { start, end: argsResult.pos },
          },
          pos: argsResult.pos,
        };
        continue;
      }

      // Try member access: expr.field -> Index with string literal key
      const memberResult = $.memberSuffix()(input, current.pos);

      if (memberResult.ok) {
        const fieldWithLoc = memberResult.value;
        current = {
          ok: true,
          value: {
            type: "Index",
            object: current.value,
            key: { type: "Literal", value: fieldWithLoc.value, loc: fieldWithLoc.loc } satisfies LiteralExpr,
            loc: { start, end: memberResult.pos },
          } as IndexExpr,
          pos: memberResult.pos,
        };
        continue;
      }

      // Try index access: expr[key]
      const indexResult = $.indexSuffix()(input, current.pos);

      if (indexResult.ok) {
        current = {
          ok: true,
          value: {
            type: "Index",
            object: current.value,
            key: indexResult.value,
            loc: { start, end: indexResult.pos },
          } as IndexExpr,
          pos: indexResult.pos,
        };
        continue;
      }

      break;
    }

    return current;
  };

  $.atom = () =>
    $.alt(
      $.lazy(() => $.objectExpr()),
      $.lazy(() => $.arrayExpr()),
      $.lazy(() => $.literal()),
      $.lazy(() => $.identExpr()),
      $.between(
        $.token("("),
        $.lazy(() => $.expr()),
        $.token(")")
      )
    );

  $.objectExpr = () =>
    $.map(
      $.between(
        $.token("{"),
        $.sepBy(
          $.lazy(() => $.property()),
          $.token(",")
        ),
        $.token("}")
      ),
      (properties, loc): ObjectExpr => ({
        type: "ObjectExpr",
        properties,
        loc,
      })
    );

  $.arrayExpr = () =>
    $.map(
      $.between(
        $.token("["),
        $.sepBy(
          $.lazy(() => $.expr()),
          $.token(",")
        ),
        $.token("]")
      ),
      (elements, loc): ArrayExpr => ({
        type: "ArrayExpr",
        elements,
        loc,
      })
    );

  $.literal = () =>
    $.alt<LiteralExpr>(
      $.map($.numberLit(), (value, loc): LiteralExpr => ({ type: "Literal", value, loc })),
      $.map($.stringLit(), (value, loc): LiteralExpr => ({ type: "Literal", value, loc })),
      $.map(
        $.keyword("true"),
        (_, loc): LiteralExpr => ({ type: "Literal", value: true, loc })
      ),
      $.map(
        $.keyword("false"),
        (_, loc): LiteralExpr => ({ type: "Literal", value: false, loc })
      ),
      $.map(
        $.keyword("null"),
        (_, loc): LiteralExpr => ({ type: "Literal", value: null, loc })
      )
    );

  $.identExpr = () => $.map($.ident(), (name, loc): IdentExpr => ({ type: "Ident", name, loc }));

  // Legacy params - delegates to lambdaParam for consistency
  $.params = () => $.sepBy($.lazy(() => $.lambdaParam()), $.token(","));

  $.args = () =>
    $.sepBy(
      $.lazy(() => $.expr()),
      $.token(",")
    );

  // === Object property pieces ===
  $.propertyKey = () => $.withLoc($.alt($.ident(), $.stringLit()));

  $.property = () =>
    $.alt(
      // Full property: key: value (key can be identifier or string)
      $.map(
        $.seq(
          $.lazy(() => $.propertyKey()),
          $.token(":"),
          $.lazy(() => $.expr())
        ),
        ([keyWithLoc, _, value]) => {
          const k = keyWithLoc as { value: string; loc: Span };
          return { key: k.value, keyLoc: k.loc, value: value as Expr };
        }
      ),
      // Shorthand property: key (same as key: key) - only for identifiers
      $.map($.ident(), (key, loc) => ({
        key,
        keyLoc: loc,
        value: { type: "Ident", name: key, loc } as IdentExpr,
      }))
    );
}

// Create the base parser
export const $parse = fix(build$parse);

// Convenience function
export function parse(input: string): Expr {
  const result = $parse.program()(input, 0);
  if (result.ok === true) {
    return result.value;
  }
  throw new Error(
    \`Parse error at position \${result.pos}: expected \${result.expected}\`
  );
}
`,
  'post.ts': `/**
 * Core pre.
 */
import { writeFileSync } from "fs";

export interface PostOps {
  write: (path: string, content: string) => void;
  [key: string]: unknown;
}

export const build$post = ($: PostOps): void => {
  $.write = (path, content) => writeFileSync(path, content);
};
`,
  'pre.ts': `import { readFileSync } from 'fs';

/**
 * Core pre.
 */
export interface PreOps {
  read: (path: string) => string;
  [key: string]: unknown;
}

export const build$pre = ($: PreOps): void => {
  $.read = (path) => readFileSync(path, 'utf-8');
};
`,
  'pretty.ts': `// Deterministic pretty-printer for values
// Used by CLI, test framework, and tracing for consistent output

export type Compact = 'always' | 'auto' | 'never';

export function prettyPrint(
  value: unknown,
  compact: Compact = 'always',
  seen = new Set<unknown>(),
  indent = 0
): string {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';

  const type = typeof value;
  if (type === 'number' || type === 'boolean') return String(value);
  if (type === 'string') return JSON.stringify(value);
  if (type === 'function') return '<function>';

  if (type === 'object') {
    if (seen.has(value)) return '<circular>';
    seen.add(value);

    if (Array.isArray(value)) {
      if (value.length === 0) return '[]';
      // Multi-line arrays when not compact and contains objects
      const hasObjects = value.some(v => typeof v === 'object' && v !== null);
      const multiLine = hasObjects && compact !== 'always';
      if (multiLine) {
        const ws = '  '.repeat(indent / 2 + 1);
        const closeWs = '  '.repeat(indent / 2);
        const items = value.map(v => ws + prettyPrint(v, compact, seen, indent + 2));
        return '[\\n' + items.join(',\\n') + '\\n' + closeWs + ']';
      } else {
        const items = value.map(v => prettyPrint(v, compact, seen, indent));
        return '[' + items.join(', ') + ']';
      }
    }

    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    if (keys.length === 0) return '{}';

    // Determine if we should use multi-line formatting
    const isCode = 'type' in obj || 'tag' in obj;
    const multiLine = compact === 'never' || (compact === 'auto' && isCode);

    if (multiLine) {
      const ws = '  '.repeat(indent / 2 + 1);
      const closeWs = '  '.repeat(indent / 2);
      const pairs = keys.map(k =>
        \`\${ws}\${JSON.stringify(k)}: \${prettyPrint(obj[k], compact, seen, indent + 2)}\`
      );
      return '{\\n' + pairs.join(',\\n') + '\\n' + closeWs + '}';
    } else {
      const pairs = keys.map(k =>
        \`\${JSON.stringify(k)}: \${prettyPrint(obj[k], compact, seen, indent)}\`
      );
      return '{' + pairs.join(', ') + '}';
    }
  }

  return String(value);
}
`,
  'util.ts': `export const fix = <Ops>(f: (ops: Ops) => void): Ops => {
  const $ = {} as Ops;
  f($);
  return $;
};
`,
  'extensions/core.ts': `// core.ts - Core Unsound language.
//
// Provides the core implementations for all phases:
//   $pre: file reading
//   $parse: base parser
//   $compile: base compiler
//   $emit: JS code generation
//   $post: file writing
//   $interpret: base interpreter
//
// Without this extension, the language is empty (can't even parse "").
import type { Extension } from '../extension.ts';
import { build$pre } from '../pre.ts';
import { build$parse } from '../parse.ts';
import { build$compile } from '../compile.ts';
import { build$emit } from '../emit.ts';
import { build$post } from '../post.ts';
import { build$interpret, defaultEnv } from '../interpret.ts';
import { build$analyze } from '../analyze.ts';

export const coreExtension: Extension = {
  name: 'core',
  description: 'Core extension providing base implementations for all phases',
  version: '1.0.0',

  $pre: ($) => {
    build$pre($);
  },

  $parse: ($) => {
    // Build parser ops directly on $ so closures reference the right object
    build$parse($);
  },

  $compile: ($) => {
    // Build compiler ops directly on $ so closures reference the right object
    build$compile($);
  },

  $emit: ($) => {
    build$emit($);
  },

  $post: ($) => {
    build$post($);
  },

  $interpret: ($) => {
    build$interpret($, defaultEnv);
  },

  $analyze: ($) => {
    build$analyze($);
  },
};

export default coreExtension;
`,
  'extensions/trace.ts': `// trace.ts - Tracing extension for debugging
// Wraps all phases to log what's happening:
//   $pre: logs file reads with timing
//   $post: logs file writes with timing
//   $interpret: logs every operation being evaluated

import type { Extension } from '../extension.ts';
import type { PreOps } from '../pre.ts';
import type { PostOps } from '../post.ts';
import type { InterpretOps, Env } from '../interpret.ts';
import { prettyPrint } from '../pretty.ts';

// Colors for terminal output
const dim = (s: string): string => \`\\x1b[2m\${s}\\x1b[0m\`;
const cyan = (s: string): string => \`\\x1b[36m\${s}\\x1b[0m\`;

let depth = 0;
const indent = () => '  '.repeat(depth);

function log(op: string, ...args: unknown[]) {
  const formatted = args.map(a => prettyPrint(a)).join(', ');
  console.log(\`\${indent()}\${op}(\${formatted})\`);
}

function logReturn(op: string, result: unknown) {
  console.log(\`\${indent()}=> \${prettyPrint(result)}\`);
}

export const traceExtension: Extension = {
  name: 'trace',
  description: 'Tracing extension that logs file I/O and interpreter operations',
  version: '1.0.0',

  $pre: ($: PreOps) => {
    const baseRead = $.read;
    $.read = (path) => {
      const start = performance.now();
      console.log(cyan(\`[pre] reading \${path}...\`));
      const content = baseRead(path);
      const elapsed = (performance.now() - start).toFixed(2);
      console.log(dim(\`[pre] read \${path} (\${content.length} bytes, \${elapsed}ms)\`));
      return content;
    };
  },

  $post: ($: PostOps) => {
    const baseWrite = $.write;
    $.write = (path, content) => {
      const start = performance.now();
      console.log(cyan(\`[post] writing \${path}...\`));
      baseWrite(path, content);
      const elapsed = (performance.now() - start).toFixed(2);
      console.log(dim(\`[post] wrote \${path} (\${content.length} bytes, \${elapsed}ms)\`));
    };
  },

  $interpret: ($: InterpretOps) => {
    const base = {
      number: $.number,
      string: $.string,
      boolean: $.boolean,
      lookup: $.lookup,
      let: $.let,
      lambda: $.lambda,
      call: $.call,
      if: $.if,
      object: $.object,
      index: $.index,
      setIndex: $.setIndex,
    };

    $.number = (n) => {
      log('number', n);
      const r = base.number(n);
      logReturn('number', r);
      return r;
    };

    $.string = (s) => {
      log('string', s);
      const r = base.string(s);
      logReturn('string', r);
      return r;
    };

    $.boolean = (b) => {
      log('boolean', b);
      const r = base.boolean(b);
      logReturn('boolean', r);
      return r;
    };

    $.lookup = ($env, name) => {
      log('lookup', name);
      const r = base.lookup($env, name);
      logReturn('lookup', r);
      return r;
    };

    $.let = ($env, name, valueFn, bodyFn) => {
      log('let', name);
      depth++;
      const r = base.let($env, name, valueFn, bodyFn);
      depth--;
      logReturn('let', r);
      return r;
    };

    $.lambda = ($env, params, bodyFn) => {
      log('lambda', params);
      const r = base.lambda($env, params, bodyFn);
      logReturn('lambda', r);
      return r;
    };

    $.call = (fn, args) => {
      log('call', fn, args);
      depth++;
      const r = base.call(fn, args);
      depth--;
      logReturn('call', r);
      return r;
    };

    $.if = (cond, thenFn, elseFn, $env) => {
      log('if', cond);
      depth++;
      const r = base.if(cond, thenFn, elseFn, $env);
      depth--;
      logReturn('if', r);
      return r;
    };

    $.object = (props) => {
      log('object', props);
      const r = base.object(props);
      logReturn('object', r);
      return r;
    };

    $.index = (obj, key) => {
      log('index', obj, key);
      const r = base.index(obj, key);
      logReturn('index', r);
      return r;
    };

    $.setIndex = (obj, key, value) => {
      log('setIndex', key, value);
      const r = base.setIndex(obj, key, value);
      logReturn('setIndex', r);
      return r;
    };
  },
};

export default traceExtension;
`
};
