#!/usr/bin/env bun
// Generates embedded-sources.ts with source code as strings

import fs from 'fs';
import path from 'path';

const sourceFiles = [
  'analyze.ts',
  'ast.ts',
  'compile-helpers.ts',
  'compile.ts',
  'emit.ts',
  'empty.ts',
  'extension.ts',
  'interpret.ts',
  'ir.ts',
  'parse.ts',
  'post.ts',
  'pre.ts',
  'pretty.ts',
  'util.ts',
  'extensions/core.ts',
  'extensions/trace.ts',
];

const entries: string[] = [];

for (const file of sourceFiles) {
  const content = fs.readFileSync(file, 'utf-8');
  // Escape backticks and ${} in the content
  const escaped = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
  entries.push(`  '${file}': \`${escaped}\``);
}

const output = `// Auto-generated by generate-embedded.ts - DO NOT EDIT
// Contains source code as strings for binary mode compilation

export const embeddedSources: Record<string, string> = {
${entries.join(',\n')}
};
`;

fs.writeFileSync('embedded-sources.ts', output);
console.log('Generated embedded-sources.ts');
